<?php
// $Id$

/**
  * @file
  * Drupal Module: highcharts
  * Provides custom functionality for building highcharts
 */

/**
 * Implementation of hook_init()
 */
/*function highcharts_init() {
  drupal_add_js( drupal_get_path('module', 'highcharts') . '/js/highcharts.js');
}*/

function pr( $something ) {
  echo "<pre>";
  print_r($something);
  echo "</pre>";
  }

function highcharts_pieChart($vid, $skip=array()) {
  drupal_set_html_head('<script type="text/javascript" src="http://www.google.com/jsapi"></script>');
	$vocab = taxonomy_vocabulary_load($vid);
	$vname = $vocab->name;
	$extendedValues = array();
	$children = highcharts_gettaxtree_nonnull($vid, $skip);
	$numChildren = count($children);
	foreach ($children as $term) {
		$currentChild++;
		$currChildName = $term->name;
		$currChildID = $term->tid;
		//$fullDataArray[$currentChild]['count'] = taxonomy_term_count_nodes($term->tid);
		$realData = views_get_view_result(chart_views, block_2, $currChildID);
		$nodeCount = count($realData);
		$fullDataArray[$currentChild]['name'] = $currChildName;
		$fullDataArray[$currentChild]['id'] = $currChildID;
		$fullDataArray[$currentChild]['count'] = $nodeCount;
	}
  usort($fullDataArray, "highcharts_cmp");
  //pr($fullDataArray);

  //drupal_add_js( '

  $data = "data.addColumn('string', 'Task');
data.addColumn('number', 'Hours per Day');
data.addRows(" . count($fullDataArray) . ");\n";
           
  foreach( $fullDataArray as $key=>$item ) {
      $data .= 'data.setValue(' . $key . ', 0, \'' . $item['name'] . "');\n";
      $data .= 'data.setValue(' . $key . ', 1, ' . $item['count'] . ");\n";
  }
  //echo $data;

$googlejs = "google.load(\"visualization\", \"1\", {packages:[\"piechart\"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();\n";


$googlejs .= $data;

$googlejs .= "

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, {width: 600, height: 440, is3D: true, title: 'Chart title'});
      }";

  drupal_add_js( $googlejs, 'inline', 'header', FALSE, FALSE, FALSE );
  echo "<div id='chart_div'></div>";
}

// From Chris' Code
function highcharts_gettaxtree_nonnull($vid, $skip=''){
	$children = taxonomy_get_children(arg(2), $vid);
      if(!$children) {
        $custom_parent = taxonomy_get_parents(arg(2));
          $parent_tree = array();
          foreach ($custom_parent as $custom_child => $key) {
            $parent_tree = taxonomy_get_tree($vid, $key->tid);
          }
          $children = $parent_tree;
      }
   	foreach ($children as $key => $value){
   		
   		$nodeCount = taxonomy_term_count_nodes($value->tid);
		if ($nodeCount == 0){
			unset($children[$key]);
			
		} else {
		}
		if($value->tid == $skip[0]){
			unset($children[$key]);
		} else {
		}
	}
	$children = array_values($children);
    return $children;
}
/**
 * Sorts array by node count.
 */
function highcharts_cmp($a, $b)
{
    if ($a['count'] == $b['count']) {
        return 0;
    }
    return ($a['count'] > $b['count']) ? -1 : 1;
}
